# -*- coding: utf-8 -*-
# pylint: skip-file
# by Roman Golev 

import Autodesk.Revit.DB as DB

def get_catlist(doc):
     catlist = {
          'Air Terminal':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_DuctTerminal),
          'Areas':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Areas),
          'Assemblies':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Assemblies),
          'Cable Tray Fitting':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_CableTrayFitting),
          'Cable Tray Runs':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_CableTrayRun),
          'Cable Trays':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_CableTray),
          'Casework':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Casework),
          'Ceilings':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Ceilings),
          'Columns':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Columns),
          'CommunicationDevices':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_CommunicationDevices),
          'Conduit Fittings':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_ConduitFitting),
          'Conduit Runs':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_ConduitRun),
          'Conduits':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Conduit),
          'Curtain Panels':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_CurtainWallPanels),
          'Curtain Systems':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_CurtaSystem),
          'Curtain Wall Mullions':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_CurtainWallMullions),
          'Data Devices':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_DataDevices),
          'Doors':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Doors),
          'Duct Accessories':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_DuctAccessory),
          'Duct Fittings':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_DuctFitting),
          'Duct Insulations':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_DuctInsulations),
          'Duct Fittings':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_DuctFitting),
          'Duct Linings':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_DuctLinings),
          'Duct Placeholders':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_PlaceHolderDucts),
          'Duct Systems':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_DuctSystem),
          'Ducts':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_DuctCurves),
          'Electrical Equipment':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_ElectricalEquipment),
          'Electrical Fixtures':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_ElectricalFixtures),
          'Entourage':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Entourage),
          'Fire Alarm Device Tags':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_FireAlarmDeviceTags),
          'Flex Ducts':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_FlexDuctCurves),
          'Flex Pipes':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_FlexPipeCurves),
          'Floors':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Floors),
          'Furniture':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Furniture),
          'Furniture Systems':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_FurnitureSystems),
          'Generic Models':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_GenericModel),
          'Grids':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Grids),
          'HVAC Zones':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_HVAC_Zones),
          'Levels':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Levels),
          'Lighting Devices':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_LightingDevices),
          'Lighting Fixtures':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_LightingFixtures),
          'Lines':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Lines),	
          'Mass':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Mass),
          'Mechanical Equipment':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_MechanicalEquipment),
          'Model Groups':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_IOSModelGroups),
          'Nurse Call Devices':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_NurseCallDevices),
          'Parking':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Parking),
          'Parts':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Parts),
          'Pipe Accessories':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_PipeAccessory),
          'Pipe Fittings':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_PipeFitting),
          'Pipe Insulations':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_PipeInsulations),
          'Pipe Placeholders':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_PlaceHolderPipes),
          'Pipes':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_PipeCurves),
          'Piping Systems':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_PipingSystem),
          'Planting':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Planting),
          'Plumbing Fixtures':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_PlumbingFixtures),
          'RVT Links':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_RvtLinks),
          'Railings':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_StairsRailing),
          'Ramps':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Ramps),
          'Roads':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Roads),
          'Roofs':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Roofs),
          'Rooms':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Rooms),
          'Security Devices':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_SecurityDevices),
          'Shaft Openings':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_ShaftOpening),
          'Site':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Site),
          'Spaces':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_MEPSpaces),
          'Specialty Equipment':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_SpecialityEquipment),
          'Sprinklers':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Sprinklers),
          'Stairs':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Stairs),
          'Structural Area Reinforcement':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_AreaRein),
          'Structural Beam Systems':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_StructuralFramingSystem),
          'Structural Columns':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_StructuralColumns),
          'Structural Connections':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_StructConnections),
          'Structural Foundations':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_StructuralFoundation),
          'Structural Framing':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_StructuralFraming),
          'Structural Path Reinforcement':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_PathRein),
          'Structural Rebar':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Rebar),
          'Structural Rebar Couplers':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Coupler),
          'Structural Stiffeners':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_StructuralStiffener),
          'Structural Trusses':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_StructuralTruss),
          'Switch System':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_SwitchSystem),
          'Telephone Devices':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_TelephoneDevices),
          'Topography':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Topography),
          'Views':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Views),
          'Walls':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Walls),
          'Windows':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Windows),
          'Wires':DB.FilteredElementCollector(doc).OfCategory(DB.BuiltInCategory.OST_Wire)
     }

     return catlist